services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: testing
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - host=${host}
      - user=${user}
      - password=${password}
      - db=${db}
      - CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - LOG_LEVEL=${LOG_LEVEL}
      - REDIS_URL=${REDIS_URL}
      - REDIS_DB=${REDIS_DB}
      - CHROMADB_HOST=${CHROMADB_HOST}
    volumes:
      - .:/app  
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "9000"]
